title: RunOn - 러닝 커뮤니티 앱
description: 러닝코스 기반 커뮤니티 앱
baseurl: ""
url: "https://runonapp.kr"

# GitHub Pages 설정
theme: minima
plugins:
  - jekyll-feed

# 네비게이션 메뉴
header_pages:
  - index.html
  - privacy-policy.html

# SEO 설정
lang: ko
timezone: Asia/Seoul

# 소셜 미디어
github_username: username
email: dlrhdkgml12@gmail.com

# 제외할 파일들
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
